set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR amd64)

set(TOOLCHAIN_PREFIX x86_64-w64-mingw32-)
execute_process(
  COMMAND which ${TOOLCHAIN_PREFIX}gcc
  OUTPUT_VARIABLE BINUTILS_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}gcc)
set(CMAKE_C_COMPILER_TARGET ${TOOLCHAIN_PREFIX}gcc)
SET(CMAKE_C_COMPILER_FORCED TRUE CACHE INTERNAL "")

set(CMAKE_MAKE_PROGRAM /usr/bin/make)

set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_INCLUDE_PATH  /usr/include/${TOOLCHAIN_PREFIX})
set(CMAKE_LIBRARY_PATH  /usr/lib/${TOOLCHAIN_PREFIX})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
