vosk = require('vosk')
vosk.init('libvosk.dll')
model = vosk.model('vosk-model-small-ru-0.22')
print('Model loaded', model)
recog = model:recognizer(16000.0)
print('Recognizer created', recog)
local f = io.open('rec.wav', 'rb')
print(recog:push(f:read('*all')))
print(recog:final())
